language: python
install:
  - pip install pep8
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
before_script:
  - "pep8 --ignore=E501  jdatetime/__init__.py"
  - sudo locale-gen fa_IR
script: python t/test.py
matrix:
    allow_failures:
        - python: "3.3"
